add_subdirectory(LaunchModule)
add_subdirectory(EngineLoopModule/Core)
add_subdirectory(EngineLoopModule/Engine)
add_subdirectory(DelegateModule)
add_subdirectory(MemoryModule)
add_subdirectory(WindowProviderModule/Core)
add_subdirectory(WindowProviderModule/Glfw)
add_subdirectory(CoreModule)
add_subdirectory(VulkanRHLModule)
add_subdirectory(MathModule)
add_subdirectory(DebugModule)