#pragma once

#define PHOTON_ENVIRONMENT_GAME 1
#define PHOTON_ENVIRONMENT_EDITOR 2
#define PHOTON_ENVIRONMENT_UNKNOWN 0

#define PHOTON_ENVIRONMENT_IS_GAME PHOTON_ENVIRONMENT == PHOTON_ENVIRONMENT_GAME
#define PHOTON_ENVIRONMENT_IS_EDITOR PHOTON_ENVIRONMENT == PHOTON_ENVIRONMENT_EDITOR
#define PHOTON_ENVIRONMENT_IS_UNKNOWN PHOTON_ENVIRONMENT == PHOTON_ENVIRONMENT_UNKNOWN